names:
  - ["Avraham", "Abraham"]
  - ["Yitzchak", "Isaac"]
  - ["Yaakov", "Jacob"]
  - ["Moshe", "Moses"]
  - ["Aharon", "Aaron"]
  - ["Shlomo", "Solomon"]
  - ["Eliyahu", "Elijah"]
  - ["Yehuda", "Judah"]
  - ["Yosef", "Joseph"]
  - ["Yonatan", "Jonathan"]
  - ["Shoshana", "Shoshanah"]
  - ["Tziporah", "Tzipora", "Zipporah"]
  - ["Devorah", "Deborah"]
  - ["Chana", "Hannah"]
  - ["Rivka", "Rebecca"]
  - Sarah
  - Leah
  - Rachel
  - Miriam
  - Naomi
  - Avigail
  - Tamar
  - Batya
  - Yael
  - Shimon
  - Levi
  - Daniel
  - Noach
  - Zev
  - "Dov-Ber"
  - Hershel
  - Moishe
  - Mendel
  - Velvel
  - Motke
  - Faige
  - Golda
  - Zlata
  - Ruchel
  - Yente
  - Baila
  - Soreh
  - Liebke