name: MVillageNamer
version: ${version}
main: gay.viktoria.mvillagenamer.VillageNamerPlugin
description: ${description}
author: Maria Taylor
website: https://viktoria.gay
api-version: '26.2'

commands:
  namechunk:
    description: Assigns names to unnamed villagers in the chunk of the executor.
    usage: /namechunk
    permission: villagenamer.namechunk
  renametag:
    description: Gives the player a name tag with the custom name "RENAMEME" for application in renaming.
    usage: /renametag
    permission: villagenamer.renametag